### ISSUE TITLE
Capitalize the outputted choices?

### ISSUE THREAD

**Issue by gregblass** [zmbacker/enum_help#12]
Is there a way to capitalize the outputted choices from an enum? For instance, I have:

<%= f.input :status, as: :radio_buttons %>

This outputs the statuses that I have declared with an enum, but they are lowercase. I just want to capitalize the first letter of each choice.

Any way to do this?

**Comment by gregblass** [comment]
Actually possible to just use css: label { text-transform: capitalize } - That solves it.

**Comment by akestner** [comment]
What about something a touch more involved, like `.humanize()` ?

**Comment by Secretmapper** [comment]
Yup humanize would be awesome
