### ISSUE TITLE
i18n array with int keys

### ISSUE THREAD

**Issue by webchi** [zmbacker/enum_help#27]
For sorting action need [["planed", 0], ["done", 1], ["loaded", 2]] with translated key.
But Model.statuses_i18n returns array with value = translated(key) and there is no integer keys to find something in database.
Maybe it's not so hard to make enums translated with integer keys?

**Comment by zmbacker** [comment]
I think you need the method Model.statuses which returns a Hash value: {"planed"=> 0, "done"=> 1, "loaded"=> 2}.   Model.statuses["planed"] can get the integer value you needed.
