### ISSUE TITLE
Adding gem to Rails 5 project changes belongs_to behavior

### ISSUE THREAD

**Issue by apolzon** [zmbacker/enum_help#28]
I'm not sure what is causing this, but when this gem is added to a Rails 5 project, belongs_to associations are no longer required by default.

Current workaround is to add required: true to all belongs_to relationships where you want the Rails 5 default behavior.

**Comment by apolzon** [comment]
As it turns out, this is due to not using ActiveSupport onload hooks to interact with active record. Please see https://github.com/rails/rails/issues/23589 and https://github.com/rails/rails/pull/25777 for more info.

Until this is resolved, moving the activerecord config into application.rb's config block will allow the setting to be set early enough in the boot cycle that the config is properly respected by descendants of AR::Base/ApplicationRecord.

**Comment by emaiax** [comment]
@apolzon see PR #34 which fixes the monkey patch.

**Comment by emaiax** [comment]
@zmbacker please merge it. Thanks!
