### ISSUE TITLE
Support Rails 7

### ISSUE THREAD

**Issue by jhjguxin** [zmbacker/enum_help#45]
Rails 7 was in stable version, Pls release package a new gem version 🙏
@zmbacker

**Comment by zmbacker** [comment]
released

**Comment by mishina2228** [comment]
Thanks a lot! And could you create a tag for v0.0.18? @zmbacker

**Comment by zmbacker** [comment]
created the tag @mishina2228

**Comment by mishina2228** [comment]
Thank you!

**Comment by maland** [comment]
running v0.0.18 i still have an issue when declaring a default value like this:

`enum status: %w[one two three], default: :one`

i receive the error: undefined method `all?' for :one:Symbol

when using the new rails 7 syntax like this:

`enum :status, %w[one two three], default: :one`

i receive the error: undefined method `statuses_i18n' for …

but it works if i only use the old syntax like this:
`enum status: %w[one two three], _default: :one`

**Comment by mishina2228** [comment]
@maland Opened PR #51 to fix the issue.
